language: c

before_install:
  - sudo apt-get update
  # sudo apt-get -f install
  # sudo apt-get upgrade
  # sudo apt-get update
  # sudo apt-get install --force-yes ia32-libs ia32-libs-multiarch
install:
  # download latest fbc release in /home/travis/build/<user>/<repo>/fb.tar.gz
  # wget -O fb.tar.gz --user-agent="WGet (Linux x86_64)" http://sourceforge.net/projects/fbc/files/latest/download
  wget -O fb.tar.gz http://sourceforge.net/projects/fbc/files/Binaries%20-%20Linux/FreeBASIC-1.04.0-linux-x86_64.tar.gz/download
  - tar zxf fb.tar.gz
  # install fbc in /home/travis/fbc
  - mkdir ~/fbc
  - cd FreeBASIC-*
  - ./install.sh -i ~/fbc
  - cd ..
  # install dependencies
  # sudo apt-get install libncurses5-dev libstdc++6 build-essential libX11-dev libXext-dev libXpm-dev libXrender-dev libXrandr-dev libgpm-dev
  # sudo apt-get install lib32ncurses5-dev
  # sudo apt-get install libx11-dev:i386 libxext-dev:i386 libxrender-dev:i386 libxpm-dev:i386 libxrandr-dev:i386 libgpm-dev:i386 libffi-dev:i386 libgl1-mesa-dev
  - sudo apt-get install libncurses5-dev libffi-dev libgl1-mesa-dev libx11-dev libxext-dev libxrender-dev libxrandr-dev libxpm-dev 
script:
  - ~/fbc/bin/fbc --version
  - make FBC=~/fbc/bin/fbc
branches:
  only:
    - master
compiler:
  - gcc
notifications:
  email: false