language: c

install:
  # download latest fbc release in /home/travis/build/<user>/<repo>/fb.tar.gz
  - wget -O fb.tar.gz --user-agent="WGet (Linux i686)" http://sourceforge.net/projects/fbc/files/latest/download
  - tar zxf fb.tar.gz
  # install fbc in /home/travis/fbc
  - mkdir ~/fbc
  - cd FreeBASIC-*-linux-x86
  - ./install.sh -i ~/fbc
  - cd ..
  # install dependencies
  # sudo apt-get install libncurses5-dev libstdc++6 build-essential libX11-dev libXext-dev libXpm-dev libXrender-dev libXrandr-dev libgpm-dev
  - sudo apt-get install gcc-multilib g++-multilib lib32ncurses5-dev
  - sudo dpkg --add-architecture i386
  - sudo apt-get update
  - sudo apt-get install libx11-dev:i386 libxext-dev:i386 libxrender-dev:i386 libxpm-dev:i386 libxrandr-dev:i386 libgpm-dev:i386 libffi-dev:i386 libgl1-mesa-dev
  - pwd
  - ls -la
  - ls -la ~/fbc
  - ls -la ~/fbc/bin
script:
  - pwd
  - ls -la
  - ls -la ~/
  - ls -la ~/fbc
  - ls -la ~/fbc/bin
  - chmod +x ~/fbc/bin/fbc
  - ~/fbc/bin/fbc --version
  - make FBC=/home/travis/fbc/bin/fbc
branches:
  only:
    - master
compiler:
  - gcc
notifications:
  email: false