language: c
install:
  - pwd
  - ls -la
  - wget -O fb.tar.gz --user-agent="WGet (Linux i686)" http://sourceforge.net/projects/fbc/files/latest/download
  - tar zxf fb.tar.gz
  - mkdir ~/fbc
  - cd FreeBASIC-*-linux-x86
  - sudo ./install.sh -i ~/fbc
  - ls ~/fbc/bin
  - sudo apt-get install libncurses5-dev libstdc++6 build-essential libX11-dev libXext-dev libXpm-dev libXrender-dev libXrandr-dev libgpm-dev
  - cd ~/fbc
  - pwd
  - ls -la
script:
  - pwd
  - ls -la
  - make FBC=~/fbc/bin/fbc
branches:
  only:
    - master
compiler:
  - gcc
notifications:
  email: false